title: curious-animal
author: Shafqat Ullah Khan
email: iamshafqatkhan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Be Curious and Share Your Curiosity With Everyone
# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username: Shasikhan # DO NOT include the @ character, or else the build will fail!
linkedin_username: shafqat-ullah-khan-25a9b8111

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
